services:
  - type: web
    name: adultos-mayores-backend
    env: node
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: centros_diurnos_db
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 24h
      - key: ENCRYPTION_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://adultos-mayores-frontend.onrender.com

  - type: static_site
    name: adultos-mayores-frontend
    env: static
    region: ohio
    plan: free
    buildCommand: cd frontend && VITE_API_URL=https://adultos-mayores-backend.onrender.com/api npm install && npm run build
    staticPublishPath: frontend/dist
